name: Optic Diff Check

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  optic-diff:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Install Optic and Spectral globally
      - name: Install Optic and Spectral CLI
        run: npm install -g @useoptic/optic @stoplight/spectral-cli

      # Run Optic diff
      - name: Run Optic Diff
        # run: optic diff current.yaml new.yaml --check
        run: optic lint current.yaml 
